export const EMAIL_TASKS = {
  SEND_EMAIL_VERIFICATION: 'SEND_EMAIL_VERIFICATION',
  SEND_TWO_FACTOR_AUTHENTICATION: 'SEND_TWO_FACTOR_AUTHENTICATION',
  SEND_FORGOT_PASSWORD: 'SEND_FORGOT_PASSWORD',
  SEND_RESET_PASSWORD: 'SEND_RESET_PASSWORD',
};

export const SMS_TASKS = {
  SEND_MOBILE_VERIFICATION: 'SEND_MOBILE_VERIFICATION',
  SEND_TWO_FACTOR_AUTHENTICATION: 'SEND_TWO_FACTOR_AUTHENTICATION',
  SEND_FORGOT_PASSWORD: 'SEND_FORGOT_PASSWORD',
  SEND_RESET_PASSWORD: 'SEND_RESET_PASSWORD',
};
